spring:
  application:
    name: GoGo

  datasource:
    url: jdbc:postgresql://localhost:5432/car_sharing
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
#    change ot true after tables are ready
    enabled: false
    baseline-on-migrate: true
#    del after tables are ready
    out-of-order: true
    ignore-migration-patterns:
        - "*:missing"
        - "*:ignored"
        - "*:pending"
# -------------------------

gogo:
  settings:
    random-number: 3