spring:
  application:
    name: GoGo

  datasource:
    url: jdbc:postgresql://localhost:5432/Car-sharing
    username: admin
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true