spring:
  application:
    name: GoGo

  datasource:
    url: jdbc:postgresql://localhost:5432/car_sharing
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

data:
  web:
    pageable:
      default-page-size: 6
      max-page-size: 15

gogo:
  settings:
    random-number: 3